// playgrounds/solid/src/routes/examples/animate.tsx
import { Motion } from "../../../../../packages/solid/src"
// import { Motion } from "@motionone/solid"

export default function Animate() {
  return (
    <Motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      hover={{ scale: 1.2 }}
      press={{ scale: 0.9 }}
      inView={{ backgroundColor: "black" }}
      transition={{ duration: 1 }}
      style={{ width: "200px", "background-color": "red", height: "200px" }}
    />
  )
}

// playgrounds/vue/pages/examples/animate.vue
<template>
  <Motion
    :initial="{ opacity: 0 }"
    :animate="{ opacity: 1 }"
    :hover="{ scale: 1.2, backgroundColor: `red`, rotate: 90 }"
    :press="{ scale: 0.9 }"
    :transition="{
      duration: 1,
      easing: [0.7, -0.46, 0.24, 1.31],
      delay: 0.5,
      repeat: 1,
    }"
    style="width: 200px; background-color: black; height: 200px"
  >
  </Motion>
  <Motion
    :initial="{ opacity: 0 }"
    :animate="{ opacity: 1 }"
    :hover="{ scale: 1.2, backgroundColor: `red`, rotate: 90 }"
    :press="{ scale: 0.9 }"
    :transition="{ duration: 1, easing: 'ease-in-out', delay: 0.5, repeat: 1 }"
    style="width: 200px; background-color: black; height: 200px"
  >
  </Motion>
  <Motion
    :initial="{ opacity: 0 }"
    :animate="{ opacity: 1 }"
    :hover="{ scale: 1.2, backgroundColor: `red`, rotate: 90 }"
    :press="{ scale: 0.9 }"
    :transition="{ duration: 1, easing: 'ease-in-out', delay: 0.5, repeat: 1 }"
    style="width: 200px; background-color: black; height: 200px"
  >
  </Motion>
  <Motion
    :initial="{ opacity: 0 }"
    :animate="{ opacity: 1 }"
    :hover="{ scale: 1.2, backgroundColor: `red`, rotate: 90 }"
    :press="{ scale: 0.9 }"
    :transition="{ duration: 1, easing: 'ease-in-out', delay: 0.5, repeat: 1 }"
    style="width: 200px; background-color: black; height: 200px"
  >
  </Motion>
</template>

<script lang="ts">
import { animate, spring } from "motion"
import { Motion } from "@motionone/vue"

export default {
  components: {
    Motion,
  },
  setup() {
    onMounted(() => {
      setTimeout(() => {
        const animation = animate((p) => {}, {
          easing: spring({ stiffness: 300, damping: 10 }),
        })
      }, 3000)
    })
  },
}
</script>
