// playgrounds/qwik/src/routes/examples/animate-prop-change/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik"
import { Motion } from "@motionone/qwik"

export default component$(() => {
  const selected = useSignal(true)

  return (
    <Motion.span
      onClick$={$(() => {
        selected.value = !selected.value
      })}
      initial={{ opacity: 0.6 }}
      animate={{
        opacity: selected.value === true ? 1 : 0.1,
        x: selected.value === true ? 0 : 50,
        transition: { duration: 1 },
      }}
      style={{
        width: "200px",
        "background-color": "purple",
        height: "200px",
        display: "flex",
        placeItems: "center",
        placeContent: "center",
      }}
      data-testid="parent"
    >
      <p>Child component</p>
    </Motion.span>
  )
})

// playgrounds/vue/pages/examples/animate-prop-change.vue
<template>
  <Motion
    :initial="{ opacity: 0.6 }"
    :animate="{
      opacity: state.isSelected ? 1 : 0.1,
      x: state.isSelected ? 0 : 50,
      transition: { duration: 1 },
    }"
    :transition="{ duration: 1 }"
    style="width: 200px; background-color: red; height: 200px"
    v-on:click="onClick"
  />
</template>

<script lang="ts">
import { reactive } from "vue"
import { Motion } from "@motionone/vue"

export default {
  components: {
    Motion,
  },
  setup() {
    const state = reactive({ isSelected: false })
    return {
      state,
      onClick: () => (state.isSelected = !state.isSelected),
    }
  },
}
</script>
