// playgrounds/solid/src/routes/examples/animate-prop-change.tsx
import { createSignal } from "solid-js"
import { Motion } from "../../../../../packages/solid/src/index"

export default function AnimatePropChange() {
  const [isSelected, setSelected] = createSignal(true)
  return (
    <Motion.Div
      onClick={() => setSelected(!isSelected())}
      initial={{ opacity: 0.6 }}
      animate={() => ({
        opacity: isSelected() ? 1 : 0.1,
        x: isSelected() ? 0 : 50,
        transition: { duration: 1 },
      })}
      transition={{ duration: 1 }}
      style={{ width: "200px", "background-color": "red", height: "200px" }}
    />
  )
}

// playgrounds/vue/pages/examples/animate-prop-change.vue
<template>
  <Motion
    :initial="{ opacity: 0.6 }"
    :animate="{
      opacity: state.isSelected ? 1 : 0.1,
      x: state.isSelected ? 0 : 50,
      transition: { duration: 1 },
    }"
    :transition="{ duration: 1 }"
    style="width: 200px; background-color: red; height: 200px"
    v-on:click="onClick"
  />
</template>

<script lang="ts">
import { reactive } from "vue"
import { Motion } from "@motionone/vue"

export default {
  components: {
    Motion,
  },
  setup() {
    const state = reactive({ isSelected: false })
    return {
      state,
      onClick: () => (state.isSelected = !state.isSelected),
    }
  },
}
</script>
