// playgrounds/vue/pages/examples/Presence-initial.vue
<template>
  <div class="container">
    <Presence>
      <Motion
        v-show="show"
        :initial="{ opacity: 0, scale: 0 }"
        :animate="{ opacity: 1, scale: 1 }"
        :exit="{ opacity: 0, scale: 0.6 }"
        class="box"
      >
      </Motion>
    </Presence>
    <button @click="show = !show">Toggle</button>
  </div>
</template>

<script>
import { Motion, Presence } from "motion/vue"

export default {
  components: { Motion, Presence },
  data() {
    return { show: true }
  },
}
</script>

<style>
.container {
  width: 100px;
  height: 150px;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}

.container button {
  cursor: pointer;
}
.box {
  width: 100px;
  height: 100px;
  border-radius: 10px;
  background-color: red;
}
</style>

// playgrounds/solid/src/routes/examples/presence-initial.tsx
import { createSignal } from "solid-js"
import { Motion } from "../../../../../packages/solid/src/index"
import { Presence } from "../../../../../packages/solid/src/presence"

import "./presence.css"

export default function PresenceInitial() {
  const [toggle, setToggle] = createSignal(false)

  return (
    <div class="container">
      <Presence when={toggle}>
        <Motion
          class="box"
          initial={{ opacity: 0, scale: 0 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0 }}
        />
      </Presence>
      <button onClick={() => setToggle(!toggle())}>
        {toggle() === true ? "Hide" : "Show"}
      </button>
    </div>
  )
}
