// packages/svelte/src/Motion.svelte
<script type="ts">
  import { setContext, getContext, onMount, afterUpdate } from "svelte"
  import { contextKey } from "./utils/context"
  import {
    createMotionState,
    createStyleString,
    AnimationOptionsWithOverrides,
    MotionState,
    Variants,
    VariantDefinition,
    InViewOptions,
  } from "@motionone/dom"

  const parentState = getContext<MotionState | undefined>(contextKey)

  let element: Element

  export let initial: VariantDefinition | undefined = undefined
  export let animate: VariantDefinition | undefined = undefined
  export let hover: VariantDefinition | undefined = undefined
  export let press: VariantDefinition | undefined = undefined
  export let inView: VariantDefinition | undefined = undefined
  export let inViewOptions: InViewOptions | undefined = undefined
  export let variants: Variants | undefined = undefined
  export let transition: AnimationOptionsWithOverrides | undefined = undefined

  const state = createMotionState(
    {
      initial,
      animate,
      hover,
      press,
      inView,
      inViewOptions,
      variants,
      transition,
    },
    parentState
  )

  const initialStyle = createStyleString(state.getTarget())

  onMount(() => state.mount(element))

  afterUpdate(() => {
    state.update({
      initial,
      animate,
      hover,
      press,
      inView,
      inViewOptions,
      variants,
      transition,
    })
  })

  setContext(contextKey, state)
</script>

<div bind:this={element} {...$$restProps} style={initialStyle} on:click>
  <slot />
</div>

// packages/qwik/src/components/motion/Motion.tsx
import { component$, Slot, useVisibleTask$, useSignal } from "@builder.io/qwik"
import {
  createMotionState,
  createStyles,
  CSSStyleDeclarationWithTransform,
  MotionKeyframes,
} from "@motionone/dom"
import {
  MotionComponentProps,
  MotionProxy,
  MotionProxyComponent,
} from "./types"

export const MotionComponent = component$<
  MotionComponentProps & {
    tag?: string
    ref?: any
    style?: MotionKeyframes
  }
>((props) => {
  const {
    tag,
    initial,
    animate,
    hover,
    press,
    inView,
    inViewOptions,
    variants,
    transition,
    // exit,
    style,
    ...rest
  } = props

  if (!tag) {
    throw new Error("tag required")
  }

  const Wrapper: any = tag

  const element = useSignal<HTMLElement>()

  const style_signal = useSignal<CSSStyleDeclarationWithTransform>(
    createStyles(style)
  )

  useVisibleTask$(({ track }) => {
    track(() => [
      initial,
      animate,
      hover,
      press,
      inView,
      inViewOptions,
      variants,
      transition,
    ])

    const state = createMotionState({
      initial,
      animate,
      hover,
      press,
      inView,
      inViewOptions,
      variants,
      transition,
    })

    if (element.value) {
      if (!state?.isMounted()) {
        state?.mount(element.value)
      }

      state?.update({
        initial,
        animate,
        hover,
        press,
        inView,
        inViewOptions,
        variants,
        transition,
      })
    }
  })

  return (
    <Wrapper
      ref={element}
      style={{
        ...style_signal.value,
        ...(typeof initial === "object" && initial),
      }}
      {...rest}
    >
      <Slot />
    </Wrapper>
  )
})

export const Motion = new Proxy(MotionComponent, {
  get:
    (_, tag: string): MotionProxyComponent<any> =>
    (props) => {
      delete props.tag
      return <MotionComponent {...props} tag={tag} />
    },
}) as unknown as MotionProxy
