// packages/solid/src/index.ts
import type { Component } from "solid-js";
import type { MotionDOMComponents, MotionComponentProps } from "./types";
import { createMotionComponent } from "./component";

const components = new Map<string, any>()
export const Motion = new Proxy(
  {},
  {
    get: (_, tag: string): Component => {
      tag = tag.toLowerCase();
      if (!components.has(tag)) {
        components.set(tag, (props: MotionComponentProps) =>
          createMotionComponent({ ...props, tag })
        )
      }
      return components.get(tag)!
    },
  }
) as MotionDOMComponents

// packages/solid/src/index.tsx
import { MotionProxy, MotionProxyComponent } from "./types"
import { Motion } from "./component"

const components = new Map<string, MotionProxyComponent<any>>()

const motionProxy = new Proxy(Motion, {
  get: (_, tag: string) => {
    tag = tag.toLowerCase()
    let component = components.get(tag)
    if (!component) {
      component = (props) => {
        delete props.tag
        return <Motion {...props} tag={tag} />
      }
      components.set(tag, component)
    }
    return component
  },
}) as MotionProxy

export { motionProxy as Motion }
