// packages/react/src/types.ts
import type {
  CSSProperties,
  DetailedHTMLFactory,
  ForwardRefExoticComponent,
  HTMLAttributes,
  PropsWithoutRef,
  ReactHTML,
  RefAttributes,
  SVGAttributes,
} from "react"
import {
  Options,
  MotionEvent,
  CustomPointerEvent,
  ViewEvent,
} from "@motionone/dom"
import type { svgElements, htmlElements } from "./utils/supported-elements"

export interface MotionEventHandlers {
  onMotionStart?: (event: MotionEvent) => void
  onMotionComplete?: (event: MotionEvent) => void
  onHoverStart?: (event: CustomPointerEvent) => void
  onHoverEnd?: (event: CustomPointerEvent) => void
  onPressStart?: (event: CustomPointerEvent) => void
  onPressEnd?: (event: CustomPointerEvent) => void
  onViewEnter?: (event: ViewEvent) => void
  onViewLeave?: (event: ViewEvent) => void
}

export interface ElementProps {
  style: CSSProperties
}

type UnionStringArray<T extends Readonly<string[]>> = T[number]

export type HTMLElements = UnionStringArray<typeof htmlElements>
export type SVGElements = UnionStringArray<typeof svgElements>

/**
 * @public
 */
export type ForwardRefComponent<T, P> = ForwardRefExoticComponent<
  PropsWithoutRef<P> & RefAttributes<T>
>

/**
 * Support for React component props
 */
type UnwrapFactoryAttributes<F> = F extends DetailedHTMLFactory<infer P, any>
  ? P
  : never
type UnwrapFactoryElement<F> = F extends DetailedHTMLFactory<any, infer P>
  ? P
  : never

type HTMLAttributesWithoutMotionProps<
  Attributes extends HTMLAttributes<Element>,
  Element extends HTMLElement
> = { [K in Exclude<keyof Attributes, keyof Options>]?: Attributes[K] }

/**
 * @public
 */
export type MotionHTMLProps<TagName extends keyof ReactHTML> =
  HTMLAttributesWithoutMotionProps<
    UnwrapFactoryAttributes<ReactHTML[TagName]>,
    UnwrapFactoryElement<ReactHTML[TagName]>
  > &
    Options &
    MotionEventHandlers

/**
 * Motion-optimised versions of React's HTML components.
 *
 * @public
 */
export type MotionHTMLComponents = {
  [K in HTMLElements]: ForwardRefComponent<
    UnwrapFactoryElement<ReactHTML[K]>,
    MotionHTMLProps<K>
  >
}

interface SVGAttributesWithoutOptions<T>
  extends Pick<
    SVGAttributes<T>,
    Exclude<keyof SVGAttributes<T>, keyof Options>
  > {}

type UnwrapSVGFactoryElement<F> = F extends React.SVGProps<infer P> ? P : never

/**
 * @public
 */
export interface MotionSVGProps<T>
  extends SVGAttributesWithoutOptions<T>,
    Options,
    MotionEventHandlers {}

/**
 * Motion-optimised versions of React's SVG components.
 *
 * @public
 */
export type MotionSVGComponents = {
  [K in SVGElements]: ForwardRefComponent<
    UnwrapSVGFactoryElement<JSX.IntrinsicElements[K]>,
    MotionSVGProps<UnwrapSVGFactoryElement<JSX.IntrinsicElements[K]>>
  >
}

export type MotionDOMComponents = MotionHTMLComponents & MotionSVGComponents

// packages/solid/src/types.ts
import type { Component, PropsWithChildren, Accessor } from "solid-js";
import type { Options } from "@motionone/dom";
import { htmlElements, svgElements } from "./utils/supported-elements";
import type {
  MotionEvent,
  VariantDefinition,
  AnimationOptionsWithOverrides,
  CustomPointerEvent,
  ViewEvent
} from "@motionone/dom";

export interface MotionEventHandlers {
  onMotionStart?: (event: MotionEvent) => void;
  onMotionComplete?: (event: MotionEvent) => void;
  onHoverStart?: (event: CustomPointerEvent) => void;
  onHoverEnd?: (event: CustomPointerEvent) => void;
  onPressStart?: (event: CustomPointerEvent) => void;
  onPressEnd?: (event: CustomPointerEvent) => void;
  onViewEnter?: (event: ViewEvent) => void;
  onViewLeave?: (event: ViewEvent) => void;
}

type UnionStringArray<T extends Readonly<string[]>> = T[number];

export type HTMLElements = UnionStringArray<typeof htmlElements>;
export type SVGElements = UnionStringArray<typeof svgElements>;

export type MotionComponentProps = Options &
  PropsWithChildren &
  MotionEventHandlers & {
    style?: object;
    class?: string;
    tag: string;
    animate?: Accessor<VariantDefinition>;
    exit?: Accessor<VariantDefinition>;
    hover?: Accessor<VariantDefinition>;
    press?: Accessor<VariantDefinition>;
    transition?: Accessor<AnimationOptionsWithOverrides> | AnimationOptionsWithOverrides;
  };

export type MotionHTMLComponents = {
  [Element in keyof HTMLElements as Capitalize<HTMLElements>]: Component<MotionComponentProps>;
};
export type MotionSVGComponents = {
  [Element in keyof SVGElements as Capitalize<HTMLElements>]: Component<MotionComponentProps>;
};

export type MotionDOMComponents = MotionHTMLComponents & MotionSVGComponents;

export type KeyframeType = Keyframe[] | PropertyIndexedKeyframes;
export type MovedElement = [el: Element, x: number, y: number];
export type MoveIntegration = (allElements: Element[]) => void;
export type ExitIntegration = (
  exitingElements: Element[],
  finish: (elements: Element[]) => void
) => void;
export type EnterIntegration = (
  enteringElements: Element[],
  finish?: ((elements: Element[]) => void) | undefined
) => void;
