// playgrounds/solid/src/routes/examples/animate.tsx
import { Motion } from "../../../../../packages/solid/src"
// import { Motion } from "@motionone/solid"

export default function Animate() {
  return (
    <Motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      hover={{ scale: 1.2 }}
      press={{ scale: 0.9 }}
      inView={{ backgroundColor: "black" }}
      transition={{ duration: 1 }}
      style={{ width: "200px", "background-color": "red", height: "200px" }}
    />
  )
}

// playgrounds/qwik/src/routes/examples/animate/index.tsx
import { component$ } from "@builder.io/qwik"
import { Motion } from "@motionone/qwik"

export default component$(() => {
  return (
    <Motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 1 }}
      hover={{ scale: 1.2 }}
      press={{ scale: 0.9 }}
      inView={{ backgroundColor: "black" }}
      style={{ width: "200px", "background-color": "red", height: "200px" }}
      data-testid="box"
    ></Motion.div>
  )
})
